// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Noticeboard.DbContexts;

#nullable disable

namespace Noticeboard.Migrations
{
    [DbContext(typeof(VacancyInfoContext))]
    partial class VacancyInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Noticeboard.Entities.Vacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("vacancies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "fsdfkmswedfmkles sdffsdfdasfswde.",
                            Name = "Software developer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "asfklnafnaejklf vsdnfgvdlskfcav .",
                            Name = "Software Analyst"
                        },
                        new
                        {
                            Id = 3,
                            Description = " Taasfafn ijafnbead asdashfa.",
                            Name = "Business Analyst"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
